config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'csv_files#index'

   get 'csv_files/index'
   get 'csv_files/show'


   get 'csv_files/import' => 'csv_files#my_import'

   resources :csv_files do
     collection {post :import}
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/csv_file.rb
class CsvFile < ApplicationRecord
  require 'csv'
  require 'activerecord-import/base'
  require 'activerecord-import/active_record/adapters/postgresql_adapter'
  has_many :users
  has_many :representations
  has_many :reservations

  def self.my_import(file)
    csv_file = CsvFile.new
    csv_file.save
    csv_file = CsvFile.new
    csv_file.save
    user = User.new
    user.save
    representation = Representation.new
    representation.save
    users = []
    reservations = []
    representations = []
    CSV.foreach(file.path, headers: true, col_sep: ';', header_converters: :symbol) do |row|
      users << User.new(:nom => row[:nom], :prenom => row[:prenom], :email => row[:email],
       :adresse => row[:adresse], :code_postal => row[:code_postal], :pays => row[:pays], :age => row[:age], :sexe => row[:sexe],
      :sexe => row[:sexe])
    end
    CSV.foreach(file.path, headers: true, col_sep: ';', header_converters: :symbol) do |row|
      reservations << Reservation.new(:numero_billet => row[:numero_billet], :reservation => row[:reservation],
       :date_reservation => row[:date_reservation], :heure_reservation => row[:heure_reservation], :cle_spectacle => row[:cle_spectacle],
       :spectacle => row[:spectacle])
    end
    CSV.foreach(file.path, headers: true, col_sep: ';', header_converters: :symbol) do |row|
      representations << Representation.new(:cle_representation => row[:cle_representation], :representation => row[:representation], :date_representation => row[:date_representation],
       :heure_representation => row[:heure_representation], :date_fin_representation => row[:date_fin_representation],
       :heure_fin_representation => row[:heure_fin_representation], :prix => row[:prix], :type_de_produit => row[:type_de_produit], :filiere_de_vente => row[:filiere_de_vente])
    end
    User.import users, recursive: true
    Reservation.import reservations, recursive: true
    Representation.import representations, recursive: true
    users.each do |user|
      user.csv_file = csv_file
      user.save
    end
    reservations.each do |reservation|
      reservation.csv_file = csv_file
      reservation.save
    end
    representations.each do |representation|
      representation.csv_file = csv_file
      representation.save
    end
  end
end

app/models/representation.rb
class Representation < ApplicationRecord
  has_many :reservations
  belongs_to :csv_file
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :csv_file
  belongs_to :representation
end

app/models/user.rb
class User < ApplicationRecord
  require 'csv'
  require 'activerecord-import/base'
  require 'activerecord-import/active_record/adapters/postgresql_adapter'
  belongs_to :csv_file
  has_many :reservations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/csv_files_controller.rb
class CsvFilesController < ApplicationController
  def index
    @users = User.all
  end

  def import
    CsvFile.my_import(params[:file])
    redirect_to root_url, notice: "Votre fichier a bien été importé"
  end

  def show
    @users = CsvFile.last.users
    @reservations = Reservation.all
    @age = @users.pluck(:age)
    @average_prices = []
    @prices_per_show = []
    @representations = Representation.all
    @show_title = @representations.pluck(:representation)
    @price = Representation.pluck(:prix)
  end

  def trim(num)
    i = num.to_i
    f = num.to_f
    i == f ? i : f
  end
  helper_method :trim

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_files_helper.rb
module CsvFilesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/csv_files/import.html.erb
<h1>CsvFiles#import</h1>
<p>Find me in app/views/csv_files/import.html.erb</p>

app/views/csv_files/index.html.erb
<div class="index_page">
  <%= flash[:notice] %>
  <div class="import_flexbox" >
    <div class="import_page">
      <h4>Importer son fichier</h4>
    </div>
    <div class="import_page">
      <%= form_tag csv_files_import_path, multipart: true do %>
        <%= file_field_tag :file, :required => 'required'%>
        <%= submit_tag "Importer" %>
      <% end %>
    </div>
    <div class="import_page">
      <% unless @users.empty? %>
        <button type="submit"> <%= link_to "Visualiser son fichier", csv_files_show_path(@csv_file, :class => "btn btn-primary") %> </button>
      <% end %>
    </div>
  </div>
</div>

app/views/csv_files/show.html.erb
<div class="container">
  <div class="container">
    <h4>Nombre de réservations:</h4>
    <%= @reservations.pluck(:numero_billet).count %>
  </div>
  <div class="container">
     <h4>le nombre d’acheteurs uniques </h4>
     <%= @users.pluck(:email).uniq.count %>
  </div>
  <div class="container">
    <h4>l’âge moyen des acheteurs:</h4>
    <% @age %>
    <% sum = @age.sum { |e| e.to_i } %>
    <%= (sum.to_f / @age.count).round %>
  </div>
  <div class="container">
    <h4>le prix moyen par représentation </h4>
    <% @representations.pluck(:representation).uniq.each do |show| %>
      <% @representations.select(:prix).where(representation: show).each do |att| %>
        <% @prices_per_show << att.attributes["prix"] %>
      <% end %>
      <% @average_prices << @prices_per_show.sum.to_f / @prices_per_show.count %>
      <% @prices_per_show.clear %>
    <% end %>
    <table>
      <% @average_prices.each_with_index do |r, i| %>
      <tr>
        <td><%= "#{@show_title.uniq[i]} => #{trim(r.round(2))}€" %></td>
      </tr>
      <% end %>
    </table>
  </div>
  <div class="back-button">
    <button type="submit"> <%= link_to "Retour", csv_files_index_path(@csv_files, :class => "btn btn-primary") %> </button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech4team</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>